; From STIX Two fonts support package.
; https://github.com/stipub/stixfonts/blob/v2.13b171/archive/STIXv2.0.0/Type1/source/latex/stix2/stix2.dtx
; Mappings to ASCII characters are removed.

::\Alpha::Α
::\Beta::Β
::\Gamma::Γ
::\Delta::Δ
::\Epsilon::Ε
::\Zeta::Ζ
::\Eta::Η
::\Theta::Θ
::\Iota::Ι
::\Kappa::Κ
::\Lambda::Λ
::\Mu::Μ
::\Nu::Ν
::\Xi::Ξ
::\Omicron::Ο
::\Pi::Π
::\Rho::Ρ
::\Sigma::Σ
::\Tau::Τ
::\Upsilon::Υ
::\Phi::Φ
::\Chi::Χ
::\Psi::Ψ
::\Omega::Ω

::\alpha::α
::\beta::β
::\gamma::γ
::\delta::δ
::\epsilon::ε
::\zeta::ζ
::\eta::η
::\theta::θ
::\iota::ι
::\kappa::κ
::\lambda::λ
::\mu::μ
::\nu::ν
::\xi::ξ
::\omicron::ο
::\pi::π
::\rho::ρ
::\sigma::σ
::\tau::τ
::\upsilon::υ
::\phi::ϕ
::\chi::χ
::\psi::ψ
::\omega::ω
::\varepsilon::ϵ
::\vartheta::ϑ
::\varpi::ϖ
::\varrho::ϱ
::\varsigma::ς
::\varphi::φ

::\nabla::∇
::\partial::∂
::\imath::𝚤
::\jmath::𝚥
::\mathsterling::£
::\mathsection::§
::\neg::¬
::\lnot::¬
::\mathparagraph::¶
::\eth::ð
::\Zbar::Ƶ
::\digamma::ϝ
::\varkappa::ϰ
::\backepsilon::϶
::\upbackepsilon::϶
::\enleadertwodots::‥
::\mathellipsis::…
::\prime::′
::\dprime::″
::\pprime::″
::\trprime::‴
::\ppprime::‴
::\qprime::⁗
::\pppprime::⁗
::\backprime::‵
::\backdprime::‶
::\backtrprime::‷
::\caretinsert::‸
::\Exclam::‼
::\hyphenbullet::⁃
::\Question::⁇
::\enclosecircle::⃝
::\enclosesquare::⃞
::\enclosediamond::⃟
::\enclosetriangle::⃤
::\Eulerconst::ℇ
::\hbar::ℏ
::\hslash::ℏ
::\Im::ℑ
::\ell::ℓ
::\wp::℘
::\Re::ℜ
::\mho::℧
::\turnediota::℩
::\Angstrom::Å
::\Finv::Ⅎ
::\aleph::ℵ
::\beth::ℶ
::\gimel::ℷ
::\daleth::ℸ
::\Game::⅁
::\sansLturned::⅂
::\sansLmirrored::⅃
::\Yup::⅄
::\PropertyLine::⅊
::\updownarrowbar::↨
::\linefeed::↴
::\carriagereturn::↵
::\barovernorthwestarrow::↸
::\barleftarrowrightarrowbar::↹
::\acwopencirclearrow::↺
::\cwopencirclearrow::↻
::\nHuparrow::⇞
::\nHdownarrow::⇟
::\leftdasharrow::⇠
::\updasharrow::⇡
::\rightdasharrow::⇢
::\downdasharrow::⇣
::\leftwhitearrow::⇦
::\upwhitearrow::⇧
::\rightwhitearrow::⇨
::\downwhitearrow::⇩
::\whitearrowupfrombar::⇪
::\forall::∀
::\complement::∁
::\exists::∃
::\nexists::∄
::\varnothing::∅
::\emptyset::∅
::\increment::∆
::\QED::∎
::\infty::∞
::\rightangle::∟
::\angle::∠
::\measuredangle::∡
::\sphericalangle::∢
::\therefore::∴
::\because::∵
::\sinewave::∿
::\top::⊤
::\bot::⊥
::\hermitmatrix::⊹
::\measuredrightangle::⊾
::\varlrtriangle::⊿
::\cdots::⋯
::\diameter::⌀
::\house::⌂
::\invnot::⌐
::\sqlozenge::⌑
::\profline::⌒
::\profsurf::⌓
::\viewdata::⌗
::\turnednot::⌙
::\varhexagonlrbonds::⌬
::\conictaper::⌲
::\topbot::⌶
::\APLnotbackslash::⍀
::\APLboxupcaret::⍓
::\APLboxquestion::⍰
::\rangledownzigzagarrow::⍼
::\hexagon::⎔
::\bbrktbrk::⎶
::\varcarriagereturn::⏎
::\obrbrak::⏠
::\ubrbrak::⏡
::\trapezium::⏢
::\benzenr::⏣
::\strns::⏤
::\fltns::⏥
::\accurrent::⏦
::\elinters::⏧
::\mathvisiblespace::␣
::\circledR::Ⓡ
::\circledS::Ⓢ
::\mdlgwhtsquare::□
::\square::□
::\Box::□
::\mdlgblksquare::■
::\blacksquare::■
::\squoval::▢
::\blackinwhitesquare::▣
::\squarehfill::▤
::\squarevfill::▥
::\squarehvfill::▦
::\squarenwsefill::▧
::\squareneswfill::▨
::\squarecrossfill::▩
::\smblksquare::▪
::\smwhtsquare::▫
::\hrectangleblack::▬
::\hrectangle::▭
::\vrectangleblack::▮
::\vrectangle::▯
::\parallelogramblack::▰
::\parallelogram::▱
::\bigblacktriangleup::▲
::\blacktriangle::▴
::\blacktriangleright::▶
::\smallblacktriangleright::▸
::\smalltriangleright::▹
::\blackpointerright::►
::\whitepointerright::▻
::\bigblacktriangledown::▼
::\bigtriangledown::▽
::\blacktriangledown::▾
::\triangledown::▿
::\blacktriangleleft::◀
::\smallblacktriangleleft::◂
::\smalltriangleleft::◃
::\blackpointerleft::◄
::\whitepointerleft::◅
::\mdlgblkdiamond::◆
::\mdlgwhtdiamond::◇
::\blackinwhitediamond::◈
::\fisheye::◉
::\mdlgwhtlozenge::◊
::\lozenge::◊
::\Diamond::◊
::\dottedcircle::◌
::\circlevertfill::◍
::\bullseye::◎
::\mdlgblkcircle::●
::\circlelefthalfblack::◐
::\circlerighthalfblack::◑
::\circlebottomhalfblack::◒
::\circletophalfblack::◓
::\circleurquadblack::◔
::\blackcircleulquadwhite::◕
::\blacklefthalfcircle::◖
::\blackrighthalfcircle::◗
::\inversebullet::◘
::\inversewhitecircle::◙
::\invwhiteupperhalfcircle::◚
::\invwhitelowerhalfcircle::◛
::\ularc::◜
::\urarc::◝
::\lrarc::◞
::\llarc::◟
::\topsemicircle::◠
::\botsemicircle::◡
::\lrblacktriangle::◢
::\llblacktriangle::◣
::\ulblacktriangle::◤
::\urblacktriangle::◥
::\circ::◦
::\smwhtcircle::◦
::\squareleftblack::◧
::\squarerightblack::◨
::\squareulblack::◩
::\squarelrblack::◪
::\trianglecdot::◬
::\triangleleftblack::◭
::\trianglerightblack::◮
::\lgwhtcircle::◯
::\squareulquad::◰
::\squarellquad::◱
::\squarelrquad::◲
::\squareurquad::◳
::\circleulquad::◴
::\circlellquad::◵
::\circlelrquad::◶
::\circleurquad::◷
::\ultriangle::◸
::\urtriangle::◹
::\lltriangle::◺
::\mdwhtsquare::◻
::\mdblksquare::◼
::\mdsmwhtsquare::◽
::\mdsmblksquare::◾
::\lrtriangle::◿
::\bigstar::★
::\bigwhitestar::☆
::\astrosun::☉
::\danger::☡
::\blacksmiley::☻
::\sun::☼
::\rightmoon::☽
::\leftmoon::☾
::\female::♀
::\male::♂
::\spadesuit::♠
::\heartsuit::♡
::\diamondsuit::♢
::\clubsuit::♣
::\varspadesuit::♤
::\varheartsuit::♥
::\vardiamondsuit::♦
::\varclubsuit::♧
::\quarternote::♩
::\eighthnote::♪

::\twonotes::♫
::\flat::♭
::\natural::♮
::\sharp::♯
::\acidfree::♾
::\dicei::⚀
::\diceii::⚁
::\diceiii::⚂
::\diceiv::⚃
::\dicev::⚄
::\dicevi::⚅
::\circledrightdot::⚆
::\circledtwodots::⚇
::\blackcircledrightdot::⚈
::\blackcircledtwodots::⚉
::\Hermaphrodite::⚥
::\mdwhtcircle::⚪
::\mdblkcircle::⚫
::\mdsmwhtcircle::⚬
::\neuter::⚲
::\checkmark::✓
::\maltese::✠
::\circledstar::✪
::\varstar::✶
::\dingasterisk::✽
::\draftingarrow::➛
::\threedangle::⟀
::\whiteinwhitetriangle::⟁
::\subsetcirc::⟃
::\supsetcirc::⟄
::\diagup::⟋
::\diagdown::⟍
::\diamondcdot::⟐
::\rdiagovfdiag::⤫
::\fdiagovrdiag::⤬
::\seovnearrow::⤭
::\neovsearrow::⤮
::\fdiagovnearrow::⤯
::\rdiagovsearrow::⤰
::\neovnwarrow::⤱
::\nwovnearrow::⤲
::\uprightcurvearrow::⤴
::\downrightcurvedarrow::⤵
::\mdsmblkcircle::⦁
::\fourvdots::⦙
::\vzigzag::⦚
::\measuredangleleft::⦛
::\rightanglesqr::⦜
::\rightanglemdot::⦝
::\angles::⦞
::\angdnr::⦟
::\gtlpar::⦠
::\sphericalangleup::⦡
::\turnangle::⦢
::\revangle::⦣
::\angleubar::⦤
::\revangleubar::⦥
::\wideangledown::⦦
::\wideangleup::⦧
::\measanglerutone::⦨
::\measanglelutonw::⦩
::\measanglerdtose::⦪
::\measangleldtosw::⦫
::\measangleurtone::⦬
::\measangleultonw::⦭
::\measangledrtose::⦮
::\measangledltosw::⦯
::\revemptyset::⦰
::\emptysetobar::⦱
::\emptysetocirc::⦲
::\emptysetoarr::⦳
::\emptysetoarrl::⦴
::\obot::⦺
::\olcross::⦻
::\odotslashdot::⦼
::\uparrowoncircle::⦽
::\circledwhitebullet::⦾
::\circledbullet::⦿
::\cirscir::⧂
::\cirE::⧃
::\boxonbox::⧉
::\triangleodot::⧊
::\triangleubar::⧋
::\triangles::⧌
::\iinfin::⧜
::\tieinfty::⧝
::\nvinfty::⧞
::\laplac::⧠
::\thermod::⧧
::\downtriangleleftblack::⧨
::\downtrianglerightblack::⧩
::\blackdiamonddownarrow::⧪
::\blacklozenge::⧫
::\circledownarrow::⧬
::\blackcircledownarrow::⧭
::\errbarsquare::⧮
::\errbarblacksquare::⧯
::\errbardiamond::⧰
::\errbarblackdiamond::⧱
::\errbarcircle::⧲
::\errbarblackcircle::⧳
::\perps::⫡
::\topcir::⫱
::\squaretopblack::⬒
::\squarebotblack::⬓
::\squareurblack::⬔
::\squarellblack::⬕
::\diamondleftblack::⬖
::\diamondrightblack::⬗
::\diamondtopblack::⬘
::\diamondbotblack::⬙
::\dottedsquare::⬚
::\lgblksquare::⬛
::\lgwhtsquare::⬜
::\vysmblksquare::⬝
::\vysmwhtsquare::⬞
::\pentagonblack::⬟
::\pentagon::⬠
::\varhexagon::⬡
::\varhexagonblack::⬢
::\hexagonblack::⬣
::\lgblkcircle::⬤
::\mdblkdiamond::⬥
::\mdwhtdiamond::⬦
::\mdblklozenge::⬧
::\mdwhtlozenge::⬨
::\smblkdiamond::⬩
::\smblklozenge::⬪
::\smwhtlozenge::⬫
::\blkhorzoval::⬬
::\whthorzoval::⬭
::\blkvertoval::⬮
::\whtvertoval::⬯
::\medwhitestar::⭐
::\medblackstar::⭑
::\smwhitestar::⭒
::\rightpentagonblack::⭓
::\rightpentagon::⭔
::\postalmark::〒
::\hzigzag::〰
::\Bbbk::𝕜
::\pm::±
::\cdotp::·
::\centerdot::·
::\times::×
::\div::÷
::\dagger::†
::\ddagger::‡
::\smblkcircle::•
::\fracslash::⁄
::\upand::⅋
::\mp::∓
::\dotplus::∔
::\reversesolidus::∖
::\ast::∗
::\vysmwhtcircle::∘
::\vysmblkcircle::∙
::\bullet::∙
::\wedge::∧
::\land::∧
::\vee::∨
::\lor::∨
::\cap::∩
::\cup::∪
::\dotminus::∸
::\invlazys::∾
::\wr::≀
::\cupleftarrow::⊌
::\cupdot::⊍
::\uplus::⊎
::\sqcap::⊓
::\sqcup::⊔
::\oplus::⊕
::\ominus::⊖
::\otimes::⊗
::\oslash::⊘
::\odot::⊙
::\circledcirc::⊚
::\circledast::⊛
::\circledequal::⊜
::\circleddash::⊝
::\boxplus::⊞
::\boxminus::⊟
::\boxtimes::⊠
::\boxdot::⊡
::\intercal::⊺
::\veebar::⊻
::\barwedge::⊼
::\barvee::⊽
::\diamond::⋄
::\smwhtdiamond::⋄
::\cdot::⋅
::\star::⋆
::\divideontimes::⋇
::\ltimes::⋉
::\rtimes::⋊
::\leftthreetimes::⋋
::\rightthreetimes::⋌
::\curlyvee::⋎
::\curlywedge::⋏
::\Cap::⋒
::\doublecap::⋒
::\Cup::⋓
::\doublecup::⋓
::\varbarwedge::⌅
::\vardoublebarwedge::⌆
::\obar::⌽
::\triangle::△
::\bigtriangleup::△
::\lhd::⊲
::\rhd::⊳
::\unlhd::⊴
::\unrhd::⊵
::\mdlgwhtcircle::○
::\boxbar::◫
::\veedot::⟇
::\wedgedot::⟑
::\lozengeminus::⟠
::\concavediamond::⟡
::\concavediamondtickleft::⟢
::\concavediamondtickright::⟣
::\whitesquaretickleft::⟤
::\whitesquaretickright::⟥
::\typecolon::⦂
::\circlehbar::⦵
::\circledvert::⦶
::\circledparallel::⦷
::\obslash::⦸
::\operp::⦹
::\olessthan::⧀
::\ogreaterthan::⧁
::\boxdiag::⧄
::\boxbslash::⧅
::\boxast::⧆
::\boxcircle::⧇
::\boxbox::⧈
::\triangleserifs::⧍
::\hourglass::⧖
::\blackhourglass::⧗
::\shuffle::⧢
::\mdlgblklozenge::⧫
::\setminus::⧵
::\dsol::⧶
::\rsolbar::⧷
::\doubleplus::⧺
::\tripleplus::⧻
::\tplus::⧾
::\tminus::⧿
::\ringplus::⨢
::\plushat::⨣
::\simplus::⨤
::\plusdot::⨥
::\plussim::⨦
::\plussubtwo::⨧
::\plustrif::⨨
::\commaminus::⨩
::\minusdot::⨪
::\minusfdots::⨫
::\minusrdots::⨬
::\opluslhrim::⨭
::\oplusrhrim::⨮
::\vectimes::⨯
::\dottimes::⨰
::\timesbar::⨱
::\btimes::⨲
::\smashtimes::⨳
::\otimeslhrim::⨴
::\otimesrhrim::⨵
::\otimeshat::⨶
::\Otimes::⨷
::\odiv::⨸
::\triangleplus::⨹
::\triangleminus::⨺
::\triangletimes::⨻
::\intprod::⨼
::\intprodr::⨽
::\fcmp::⨾
::\amalg::⨿
::\capdot::⩀
::\uminus::⩁
::\barcup::⩂
::\barcap::⩃
::\capwedge::⩄
::\cupvee::⩅
::\cupovercap::⩆
::\capovercup::⩇
::\cupbarcap::⩈
::\capbarcup::⩉
::\twocups::⩊
::\twocaps::⩋
::\closedvarcup::⩌
::\closedvarcap::⩍
::\Sqcap::⩎
::\Sqcup::⩏
::\closedvarcupsmashprod::⩐
::\wedgeodot::⩑
::\veeodot::⩒
::\Wedge::⩓
::\Vee::⩔
::\wedgeonwedge::⩕
::\veeonvee::⩖
::\bigslopedvee::⩗
::\bigslopedwedge::⩘
::\wedgemidvert::⩚
::\veemidvert::⩛
::\midbarwedge::⩜
::\midbarvee::⩝
::\doublebarwedge::⩞
::\wedgebar::⩟
::\wedgedoublebar::⩠
::\varveebar::⩡
::\doublebarvee::⩢
::\veedoublebar::⩣
::\dsub::⩤
::\rsub::⩥
::\eqqplus::⩱
::\pluseqq::⩲
::\interleave::⫴
::\nhVvert::⫵
::\threedotcolon::⫶
::\trslash::⫻
::\sslash::⫽
::\talloblong::⫾
::\closure::⁐
::\vertoverlay::⃒
::\leftarrow::←
::\gets::←
::\uparrow::↑
::\rightarrow::→
::\to::→
::\downarrow::↓
::\leftrightarrow::↔
::\updownarrow::↕
::\nwarrow::↖
::\nearrow::↗
::\searrow::↘
::\swarrow::↙
::\nleftarrow::↚
::\nrightarrow::↛
::\leftwavearrow::↜
::\rightwavearrow::↝
::\twoheadleftarrow::↞
::\twoheaduparrow::↟
::\twoheadrightarrow::↠
::\twoheaddownarrow::↡
::\leftarrowtail::↢
::\rightarrowtail::↣
::\mapsfrom::↤
::\mapsup::↥
::\mapsto::↦
::\mapsdown::↧
::\hookleftarrow::↩
::\hookrightarrow::↪
::\looparrowleft::↫
::\looparrowright::↬
::\leftrightsquigarrow::↭
::\nleftrightarrow::↮
::\downzigzagarrow::↯
::\Lsh::↰
::\Rsh::↱
::\Ldsh::↲
::\Rdsh::↳
::\curvearrowleft::↶
::\curvearrowright::↷
::\circlearrowleft::↺
::\circlearrowright::↻
::\leftharpoonup::↼
::\leftharpoondown::↽
::\upharpoonright::↾
::\restriction::↾
::\upharpoonleft::↿
::\rightharpoonup::⇀
::\rightharpoondown::⇁
::\downharpoonright::⇂
::\downharpoonleft::⇃
::\rightleftarrows::⇄
::\updownarrows::⇅
::\leftrightarrows::⇆
::\leftleftarrows::⇇
::\upuparrows::⇈
::\rightrightarrows::⇉
::\downdownarrows::⇊
::\leftrightharpoons::⇋
::\rightleftharpoons::⇌
::\nLeftarrow::⇍
::\nLeftrightarrow::⇎
::\nRightarrow::⇏
::\Leftarrow::⇐
::\Uparrow::⇑
::\Rightarrow::⇒
::\Downarrow::⇓
::\Leftrightarrow::⇔
::\Updownarrow::⇕
::\Nwarrow::⇖
::\Nearrow::⇗
::\Searrow::⇘
::\Swarrow::⇙
::\Lleftarrow::⇚
::\Rrightarrow::⇛
::\leftsquigarrow::⇜
::\rightsquigarrow::⇝
::\leadsto::⇝
::\barleftarrow::⇤
::\rightarrowbar::⇥
::\circleonrightarrow::⇴
::\downuparrows::⇵
::\rightthreearrows::⇶
::\nvleftarrow::⇷
::\nvrightarrow::⇸
::\nvleftrightarrow::⇹
::\nVleftarrow::⇺
::\nVrightarrow::⇻
::\nVleftrightarrow::⇼
::\leftarrowtriangle::⇽
::\rightarrowtriangle::⇾
::\leftrightarrowtriangle::⇿
::\in::∈
::\notin::∉
::\smallin::∊
::\ni::∋
::\owns::∋
::\nni::∌
::\smallni::∍
::\propto::∝
::\mid::∣
::\nmid::∤
::\parallel::∥
::\nparallel::∦
::\Colon::∷
::\dashcolon::∹
::\dotsminusdots::∺
::\kernelcontraction::∻
::\sim::∼
::\thicksim::∼
::\backsim::∽
::\nsim::≁
::\eqsim::≂
::\simeq::≃
::\nsime::≄
::\cong::≅
::\simneqq::≆
::\ncong::≇
::\approx::≈
::\napprox::≉
::\approxeq::≊
::\approxident::≋
::\backcong::≌
::\asymp::≍
::\Bumpeq::≎
::\bumpeq::≏
::\doteq::≐
::\Doteq::≑
::\doteqdot::≑
::\fallingdotseq::≒
::\risingdotseq::≓
::\coloneq::≔
::\eqcolon::≕
::\eqcirc::≖
::\circeq::≗
::\arceq::≘
::\wedgeq::≙
::\veeeq::≚
::\stareq::≛
::\triangleq::≜
::\Deltaeq::≜
::\eqdef::≝
::\defeq::≝
::\measeq::≞
::\questeq::≟
::\ne::≠
::\neq::≠
::\equiv::≡
::\nequiv::≢
::\Equiv::≣
::\leq::≤
::\le::≤
::\geq::≥
::\ge::≥
::\leqq::≦
::\geqq::≧
::\lneqq::≨
::\lvertneqq::≨
::\gneqq::≩
::\gvertneqq::≩
::\ll::≪
::\gg::≫
::\between::≬
::\nasymp::≭
::\nless::≮
::\ngtr::≯
::\nleq::≰
::\ngeq::≱
::\lesssim::≲
::\gtrsim::≳
::\nlesssim::≴
::\ngtrsim::≵
::\lessgtr::≶
::\gtrless::≷
::\nlessgtr::≸
::\ngtrless::≹
::\prec::≺
::\succ::≻
::\preccurlyeq::≼
::\succcurlyeq::≽
::\precsim::≾
::\succsim::≿
::\nprec::⊀
::\nsucc::⊁
::\subset::⊂
::\supset::⊃
::\nsubset::⊄
::\nsupset::⊅
::\subseteq::⊆
::\supseteq::⊇
::\nsubseteq::⊈
::\nsupseteq::⊉
::\subsetneq::⊊
::\varsubsetneq::⊊
::\supsetneq::⊋
::\varsupsetneq::⊋
::\sqsubset::⊏
::\sqsupset::⊐
::\sqsubseteq::⊑
::\sqsupseteq::⊒
::\vdash::⊢
::\dashv::⊣
::\assert::⊦
::\models::⊧
::\vDash::⊨
::\Vdash::⊩
::\Vvdash::⊪
::\VDash::⊫
::\nvdash::⊬
::\nvDash::⊭
::\nVdash::⊮
::\nVDash::⊯
::\prurel::⊰
::\scurel::⊱
::\vartriangleleft::⊲
::\vartriangleright::⊳
::\trianglelefteq::⊴
::\trianglerighteq::⊵
::\origof::⊶
::\imageof::⊷
::\multimap::⊸
::\bowtie::⋈
::\backsimeq::⋍
::\Subset::⋐
::\Supset::⋑
::\pitchfork::⋔
::\equalparallel::⋕
::\lessdot::⋖
::\gtrdot::⋗
::\lll::⋘
::\llless::⋘
::\ggg::⋙
::\gggtr::⋙
::\lesseqgtr::⋚
::\gtreqless::⋛
::\eqless::⋜
::\eqgtr::⋝
::\curlyeqprec::⋞
::\curlyeqsucc::⋟
::\npreccurlyeq::⋠
::\nsucccurlyeq::⋡
::\nsqsubseteq::⋢
::\nsqsupseteq::⋣
::\sqsubsetneq::⋤
::\sqsupsetneq::⋥
::\lnsim::⋦
::\gnsim::⋧
::\precnsim::⋨
::\succnsim::⋩
::\nvartriangleleft::⋪
::\nvartriangleright::⋫
::\ntrianglelefteq::⋬
::\ntrianglerighteq::⋭
::\vdots::⋮
::\adots::⋰
::\ddots::⋱
::\disin::⋲
::\varisins::⋳
::\isins::⋴
::\isindot::⋵
::\varisinobar::⋶
::\isinobar::⋷
::\isinvb::⋸
::\isinE::⋹
::\nisd::⋺
::\varnis::⋻
::\nis::⋼
::\varniobar::⋽
::\niobar::⋾
::\bagmember::⋿
::\frown::⌢
::\smile::⌣
::\APLnotslash::⌿
::\vartriangle::▵
::\perp::⟂
::\bsolhsub::⟈
::\suphsol::⟉
::\upin::⟒
::\pullback::⟓
::\pushout::⟔
::\DashVDash::⟚
::\dashVdash::⟛
::\multimapinv::⟜
::\vlongdash::⟝
::\longdashv::⟞
::\cirbot::⟟
::\UUparrow::⟰
::\DDownarrow::⟱
::\acwgapcirclearrow::⟲
::\cwgapcirclearrow::⟳
::\rightarrowonoplus::⟴
::\longleftarrow::⟵
::\longrightarrow::⟶
::\longleftrightarrow::⟷
::\Longleftarrow::⟸
::\Longrightarrow::⟹
::\Longleftrightarrow::⟺
::\longmapsfrom::⟻
::\longmapsto::⟼
::\Longmapsfrom::⟽
::\Longmapsto::⟾
::\longrightsquigarrow::⟿
::\nvtwoheadrightarrow::⤀
::\nVtwoheadrightarrow::⤁
::\nvLeftarrow::⤂
::\nvRightarrow::⤃
::\nvLeftrightarrow::⤄
::\twoheadmapsto::⤅
::\Mapsfrom::⤆
::\Mapsto::⤇
::\downarrowbarred::⤈
::\uparrowbarred::⤉
::\Uuparrow::⤊
::\Ddownarrow::⤋
::\leftbkarrow::⤌
::\rightbkarrow::⤍
::\leftdbkarrow::⤎
::\dashleftarrow::⤎
::\dbkarow::⤏
::\dashrightarrow::⤏
::\drbkarow::⤐
::\rightdotarrow::⤑
::\baruparrow::⤒
::\downarrowbar::⤓
::\nvrightarrowtail::⤔
::\nVrightarrowtail::⤕
::\twoheadrightarrowtail::⤖
::\nvtwoheadrightarrowtail::⤗
::\nVtwoheadrightarrowtail::⤘
::\lefttail::⤙
::\righttail::⤚
::\leftdbltail::⤛
::\rightdbltail::⤜
::\diamondleftarrow::⤝
::\rightarrowdiamond::⤞
::\diamondleftarrowbar::⤟
::\barrightarrowdiamond::⤠
::\nwsearrow::⤡
::\neswarrow::⤢
::\hknwarrow::⤣
::\hknearrow::⤤
::\hksearow::⤥
::\hkswarow::⤦
::\tona::⤧
::\toea::⤨
::\tosa::⤩
::\towa::⤪
::\rightcurvedarrow::⤳
::\leftdowncurvedarrow::⤶
::\rightdowncurvedarrow::⤷
::\cwrightarcarrow::⤸
::\acwleftarcarrow::⤹
::\acwoverarcarrow::⤺
::\acwunderarcarrow::⤻
::\curvearrowrightminus::⤼
::\curvearrowleftplus::⤽
::\cwundercurvearrow::⤾
::\ccwundercurvearrow::⤿
::\acwcirclearrow::⥀
::\cwcirclearrow::⥁
::\rightarrowshortleftarrow::⥂
::\leftarrowshortrightarrow::⥃
::\shortrightarrowleftarrow::⥄
::\rightarrowplus::⥅
::\leftarrowplus::⥆
::\rightarrowx::⥇
::\leftrightarrowcircle::⥈
::\twoheaduparrowcircle::⥉
::\leftrightharpoonupdown::⥊
::\leftrightharpoondownup::⥋
::\updownharpoonrightleft::⥌
::\updownharpoonleftright::⥍
::\leftrightharpoonupup::⥎
::\updownharpoonrightright::⥏
::\leftrightharpoondowndown::⥐
::\updownharpoonleftleft::⥑
::\barleftharpoonup::⥒
::\rightharpoonupbar::⥓
::\barupharpoonright::⥔
::\downharpoonrightbar::⥕
::\barleftharpoondown::⥖
::\rightharpoondownbar::⥗
::\barupharpoonleft::⥘
::\downharpoonleftbar::⥙
::\leftharpoonupbar::⥚
::\barrightharpoonup::⥛
::\upharpoonrightbar::⥜
::\bardownharpoonright::⥝
::\leftharpoondownbar::⥞
::\barrightharpoondown::⥟
::\upharpoonleftbar::⥠
::\bardownharpoonleft::⥡
::\leftharpoonsupdown::⥢
::\upharpoonsleftright::⥣
::\rightharpoonsupdown::⥤
::\downharpoonsleftright::⥥
::\leftrightharpoonsup::⥦
::\leftrightharpoonsdown::⥧
::\rightleftharpoonsup::⥨
::\rightleftharpoonsdown::⥩
::\leftharpoonupdash::⥪
::\dashleftharpoondown::⥫
::\rightharpoonupdash::⥬
::\dashrightharpoondown::⥭
::\updownharpoonsleftright::⥮
::\downupharpoonsleftright::⥯
::\rightimply::⥰
::\equalrightarrow::⥱
::\similarrightarrow::⥲
::\leftarrowsimilar::⥳
::\rightarrowsimilar::⥴
::\rightarrowapprox::⥵
::\ltlarr::⥶
::\leftarrowless::⥷
::\gtrarr::⥸
::\subrarr::⥹
::\leftarrowsubset::⥺
::\suplarr::⥻
::\leftfishtail::⥼
::\rightfishtail::⥽
::\upfishtail::⥾
::\downfishtail::⥿
::\rtriltri::⧎
::\ltrivb::⧏
::\vbrtri::⧐
::\lfbowtie::⧑
::\rfbowtie::⧒
::\fbowtie::⧓
::\lftimes::⧔
::\rftimes::⧕
::\dualmap::⧟
::\lrtriangleeq::⧡
::\eparsl::⧣
::\smeparsl::⧤
::\eqvparsl::⧥
::\gleichstark::⧦
::\ruledelayed::⧴
::\veeonwedge::⩙
::\eqdot::⩦
::\dotequiv::⩧
::\equivVert::⩨
::\equivVvert::⩩
::\dotsim::⩪
::\simrdots::⩫
::\simminussim::⩬
::\congdot::⩭
::\asteq::⩮
::\hatapprox::⩯
::\approxeqq::⩰
::\eqqsim::⩳
::\Coloneq::⩴
::\eqeq::⩵
::\eqeqeq::⩶
::\ddotseq::⩷
::\equivDD::⩸
::\ltcir::⩹
::\gtcir::⩺
::\ltquest::⩻
::\gtquest::⩼
::\leqslant::⩽
::\geqslant::⩾
::\lesdot::⩿
::\gesdot::⪀
::\lesdoto::⪁
::\gesdoto::⪂
::\lesdotor::⪃
::\gesdotol::⪄
::\lessapprox::⪅
::\gtrapprox::⪆
::\lneq::⪇
::\gneq::⪈
::\lnapprox::⪉
::\gnapprox::⪊
::\lesseqqgtr::⪋
::\gtreqqless::⪌
::\lsime::⪍
::\gsime::⪎
::\lsimg::⪏
::\gsiml::⪐
::\lgE::⪑
::\glE::⪒
::\lesges::⪓
::\gesles::⪔
::\eqslantless::⪕
::\eqslantgtr::⪖
::\elsdot::⪗
::\egsdot::⪘
::\eqqless::⪙
::\eqqgtr::⪚
::\eqqslantless::⪛
::\eqqslantgtr::⪜
::\simless::⪝
::\simgtr::⪞
::\simlE::⪟
::\simgE::⪠
::\Lt::⪡
::\Gt::⪢
::\partialmeetcontraction::⪣
::\glj::⪤
::\gla::⪥
::\ltcc::⪦
::\gtcc::⪧
::\lescc::⪨
::\gescc::⪩
::\smt::⪪
::\lat::⪫
::\smte::⪬
::\late::⪭
::\bumpeqq::⪮
::\preceq::⪯
::\succeq::⪰
::\precneq::⪱
::\succneq::⪲
::\preceqq::⪳
::\succeqq::⪴
::\precneqq::⪵
::\succneqq::⪶
::\precapprox::⪷
::\succapprox::⪸
::\precnapprox::⪹
::\succnapprox::⪺
::\Prec::⪻
::\Succ::⪼
::\subsetdot::⪽
::\supsetdot::⪾
::\subsetplus::⪿
::\supsetplus::⫀
::\submult::⫁
::\supmult::⫂
::\subedot::⫃
::\supedot::⫄
::\subseteqq::⫅
::\supseteqq::⫆
::\subsim::⫇
::\supsim::⫈
::\subsetapprox::⫉
::\supsetapprox::⫊
::\subsetneqq::⫋
::\varsubsetneqq::⫋
::\supsetneqq::⫌
::\varsupsetneqq::⫌
::\lsqhook::⫍
::\rsqhook::⫎
::\csub::⫏
::\csup::⫐
::\csube::⫑
::\csupe::⫒
::\subsup::⫓
::\supsub::⫔
::\subsub::⫕
::\supsup::⫖
::\suphsub::⫗
::\supdsub::⫘
::\forkv::⫙
::\topfork::⫚
::\mlcp::⫛
::\forks::⫝̸
::\forksnot::⫝
::\shortlefttack::⫞
::\shortdowntack::⫟
::\shortuptack::⫠
::\vDdash::⫢
::\dashV::⫣
::\Dashv::⫤
::\DashV::⫥
::\varVdash::⫦
::\Barv::⫧
::\vBar::⫨
::\vBarv::⫩
::\barV::⫪
::\Vbar::⫫
::\Not::⫬
::\bNot::⫭
::\revnmid::⫮
::\cirmid::⫯
::\midcir::⫰
::\nhpar::⫲
::\parsim::⫳
::\lllnest::⫷
::\gggnest::⫸
::\leqqslant::⫹
::\geqqslant::⫺
::\circleonleftarrow::⬰
::\leftthreearrows::⬱
::\leftarrowonoplus::⬲
::\longleftsquigarrow::⬳
::\nvtwoheadleftarrow::⬴
::\nVtwoheadleftarrow::⬵
::\twoheadmapsfrom::⬶
::\twoheadleftdbkarrow::⬷
::\leftdotarrow::⬸
::\nvleftarrowtail::⬹
::\nVleftarrowtail::⬺
::\twoheadleftarrowtail::⬻
::\nvtwoheadleftarrowtail::⬼
::\nVtwoheadleftarrowtail::⬽
::\leftarrowx::⬾
::\leftcurvedarrow::⬿
::\equalleftarrow::⭀
::\bsimilarleftarrow::⭁
::\leftarrowbackapprox::⭂
::\rightarrowgtr::⭃
::\rightarrowsupset::⭄
::\LLeftarrow::⭅
::\RRightarrow::⭆
::\bsimilarrightarrow::⭇
::\rightarrowbackapprox::⭈
::\similarleftarrow::⭉
::\leftarrowapprox::⭊
::\leftarrowbsimilar::⭋
::\rightarrowbsimilar::⭌

::\int::∫
::\int::∫
::\iint::∬
::\iiint::∭
::\iiiint::⨌
::\oint::∮
::\oiint::∯
::\oiiint::∰
::\intclockwise::∱
::\varointclockwise::∲
::\coint::∲
::\ointctrclockwise::∳
::\aoint::∳
::\sumint::⨋
::\iiiint::⨌
::\intbar::⨍
::\intBar::⨎
::\fint::⨏
::\cirfnint::⨐
::\awint::⨑
::\rppolint::⨒
::\scpolint::⨓
::\npolint::⨔
::\pointint::⨕
::\sqint::⨖
::\intlarhk::⨗
::\intx::⨘
::\intcap::⨙
::\intcup::⨚
::\upint::⨛
::\lowint::⨜

::\ulcorner::⌜
::\urcorner::⌝
::\llcorner::⌞
::\lrcorner::⌟
::\Lbrbrak::⟬
::\Rbrbrak::⟭
::\llparenthesis::⦇
::\rrparenthesis::⦈
::\llangle::⦉
::\rrangle::⦊
::\lbrackubar::⦋
::\rbrackubar::⦌
::\lbrackultick::⦍
::\rbracklrtick::⦎
::\lbracklltick::⦏
::\rbrackurtick::⦐
::\langledot::⦑
::\rangledot::⦒
::\lparenless::⦓
::\rparengtr::⦔
::\Lparengtr::⦕
::\Rparenless::⦖
::\lblkbrbrak::⦗
::\rblkbrbrak::⦘
::\lvzigzag::⧘
::\rvzigzag::⧙
::\Lvzigzag::⧚
::\Rvzigzag::⧛
::\lcurvyangle::⧼
::\rcurvyangle::⧽
::\lbrbrak::❲
::\rbrbrak::❳
::\lbag::⟅
::\rbag::⟆

::\sum::∑
::\prod::∏
::\coprod::∐
::\bigwedge::⋀
::\bigvee::⋁
::\bigcap::⋂
::\bigcup::⋃
::\bigudot::⨃
::\biguplus::⨄
::\bigodot::⨀
::\bigoplus::⨁
::\bigotimes::⨂
::\bigsqcap::⨅
::\bigsqcup::⨆
::\bigtimes::⨉
::\Join::⨝

::\acute::́
::\bar::̅
::\Bar::̿
::\breve::̆
::\check::̌
::\dot::̇
::\ddot::̈
::\dddot::⃛
::\ddddot::⃜
::\grave::̀
::\hat::̂
::\hvec::⃑
::\rhvec::⃑
::\lhvec::⃐
::\lvec::⃖
::\vec::⃗
::\overbar::¯
::\overbrace::⏞
::\overbracket::⎴
::\overline::‾
::\overparen::⏜
::\overshell::⏠
::\tilde::̃
::\tvec::⃡
::\ubar::̲
::\Ubar::̳
::\underbrace::⏟
::\underbracket::⎵
::\underparen::⏝
::\undershell::⏡

; non-standard
::\quad:: 
::\ensp:: 
::\emsp:: 
::\nbsp:: 
::\zwsp::​
::\sqrt::√
::\funcapply::⁡
::\itimes::⁢
::\iplus::⁤
::\icomma::⁣

::\all::∀
::\==::≡
::\===::≣
::\box::□
::\bra::⟨
::\ket::⟩
::\break::⤶
::\cbrt::∛
::\fourthroot::∜
::\dd::ⅆ
::\Dd::ⅅ
::\DD::ⅅ
::\ee::ⅇ
::\ii::ⅈ
::\jj::ⅉ
::\degree::°
::\degc::℃
::\degf::℉
::\lBrack::⟦
::\rBrack::⟧
::\lAngle::⟪
::\rAngle::⟫
::\lmoust::⎰
::\lmoustache::⎰
::\rmoust::⎱
::\rmoustache::⎱
::\lrhar::⇋
::\ratio::∶
::\rect::▭
::\oval::⬭
::\circle::○
