#!/bin/bash

# short edge?
if true
then
	if (( $1 > 0 && $1 % 4 == 0 ))
	then
		pdfjam --landscape --paper a4paper --suffix booklet --booklet true --signature "$@"
		#pdfjam --landscape --suffix book --booklet true --signature "$@"
	else
		echo "pdfbook n input.pdf"
		echo "where n is divisible by 4."
	fi
else
	(kpsewhich everyshi.sty >/dev/null) || {
		echo "the 'everyshi' package is not installed."; exit 1
	}
	exec pdfjam --landscape --suffix book --signature 4 \
		--preamble '\usepackage{everyshi}
			\makeatletter
			\EveryShipout{\ifodd\c@page\pdfpageattr{/Rotate 180}\fi}
			\makeatother
			' "$@"
fi
